<?php

/**
 * JEWE configuration file
 */

final class config {

	public string $language         = 'en';
	public bool $translate          = false;

	public string $startPage        = 'main.html';
	public string $title            = 'JEWE2 Webpage';
	public string $logo             = 'logo.jpg';
	public string $logoWidth        = '640';
	public string $logoHeight       = '480';

	public bool $skipFirstChapter = true;
	public bool $showChapterIndex = true;
}
